version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    assignees: ["przemeklal"]
    reviewers: ["przemeklal"]
    open-pull-requests-limit: 6
    schedule:
      day: "monday"
      timezone: "10:00 CEST"
      interval: "weekly"
