name: Unit and Integration Tests

on:
  push:
    branches: [main]
  pull_request:
  workflow_call:

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  test:
    name: Unit and Integration Tests on ${{ matrix.platform }} Python ${{ matrix.python }}
    needs: [lint]
    strategy:
      matrix:
        python: ["3.8", "3.9", "3.10", "3.11"]
        platform: ["ubuntu-18.04", "ubuntu-20.04", "ubuntu-22.04"]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}

      - name: Install tox
        run: python -m pip install -U tox
      
      - name: Configure LXD
        run: |
          sudo adduser "${USER}" lxd
          sudo newgrp lxd
          sudo lxd init --auto
          sudo lxc network set lxdbr0 ipv6.address none
          sudo chmod a+wr /var/snap/lxd/common/lxd/unix.socket

      - name: Install Juju
        run: |
          sudo snap install juju --channel=2.9/stable --classic

      - name: Bootstrap Juju
        run: |
          juju bootstrap localhost

      - name: Install Charmcraft
        run: |
          sudo snap install charmcraft --classic

      - name: Run unit tests
        run: python -m tox -e unit

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Run integration tests
        run: python -m tox -e integration
