name: Release
on:
  push:
    branches: [main]

jobs:
  release:
    name: Release to edge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Upload charm to charmhub
        uses: canonical/charming-actions/upload-charm@2.2.0
        with:
          credentials: "${{ secrets.CHARMCRAFT_AUTH }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          channel: latest/edge
      # TODO: fix non-existent tracks on charmhub
      #- name: Upload charm to focal/edge on charmhub
      #  uses: canonical/charming-actions/upload-charm@2.2.0
      #  with:
      #    credentials: "${{ secrets.CHARMCRAFT_AUTH }}"
      #    github-token: "${{ secrets.GITHUB_TOKEN }}"
      #    built-charm-path: local-juju-users_ubuntu-20.04-amd64.charm
      #    channel: focal/edge
      #- name: Upload charm to bionic/edge on charmhub
      #  uses: canonical/charming-actions/upload-charm@2.2.0
      #  with:
      #    credentials: "${{ secrets.CHARMCRAFT_AUTH }}"
      #    github-token: "${{ secrets.GITHUB_TOKEN }}"
      #    built-charm-path: local-juju-users_ubuntu-18.04-amd64.charm
      #    channel: bionic/edge
