name: Release
on:
  push:
    branches: [main]

jobs:
  release:
    name: Release to edge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install charmcraft
        run: sudo snap install charmcraft --classic
      - name: Install jq
        run: sudo snap install jq
      - name: Install LXD
        run: |
          sudo snap install lxd --channel=latest/stable
          sudo snap refresh lxd
          sudo groupadd --force --system lxd
          sudo usermod --append --groups lxd $USER
          newgrp lxd
          sudo snap start lxd
          sudo lxd waitready --timeout=30
          sudo lxd init --auto          
      - name: Pack the charm
        run: |
          sudo charmcraft pack
          file *.charm
      - name: Upload and release
        env:
          CHARMCRAFT_AUTH: ${{ secrets.CHARMCRAFT_AUTH }}
        run: |
          charmcraft upload local-juju-users_ubuntu-18.04-amd64.charm --format json | tee upload_bionic.json
          charmcraft release local-juju-users --revision $(jq .revision upload_bionic.json) --channel=bionic/edge
          charmcraft release local-juju-users --revision $(jq .revision upload_bionic.json) --channel=latest/edge
          charmcraft upload local-juju-users_ubuntu-20.04-amd64.charm --format json | tee upload_focal.json
          charmcraft release local-juju-users --revision $(jq .revision upload_focal.json) --channel=focal/edge
          charmcraft release local-juju-users --revision $(jq .revision upload_focal.json) --channel=latest/edge
          charmcraft upload local-juju-users_ubuntu-22.04-amd64.charm --format json | tee upload_jammy.json
          charmcraft release local-juju-users --revision $(jq .revision upload_jammy.json) --channel=jammy/edge
          charmcraft release local-juju-users --revision $(jq .revision upload_jammy.json) --channel=latest/edge
