name: Release
on:
  push:
    branches: [main]

jobs:
  release:
    name: Release to edge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install charmcraft
        run: sudo snap install charmcraft --classic
      - name: Install jq
        run: sudo snap install jq
      - name: Pack the charm
        run: sudo charmcraft pack
      - name: Upload bionic/edge
        run: charmcraft upload local-juju-users_ubuntu-18.04-amd64.charm --format json | tee upload_bionic.json
      - name: Release bionic/edge
        run: charmcraft release local-juju-users --revision $(jq .revision upload_bionic.json) --channel=bionic/edge
      - name: Upload focal/edge
        run: charmcraft upload local-juju-users_ubuntu-20.04-amd64.charm --format json | tee upload_focal.json
      - name: Release focal/edge
        run: charmcraft release local-juju-users --revision $(jq .revision upload_focal.json) --channel=focal/edge
      - name: Upload jammy/edge
        run: charmcraft upload local-juju-users_ubuntu-22.04-amd64.charm --format json | tee upload_jammy.json
      - name: Release jammy/edge
        run: charmcraft release local-juju-users --revision $(jq .revision upload_jammy.json) --channel=jammy/edge
      - name: Release latest/edge
        run: charmcraft release local-juju-users --revision $(jq .revision upload_jammy.json) --channel=latest/edge
